avator_1:
 preparation: True # your can set it to False if you want to use the existing avator, it will save time
 bbox_shift: 12
 video_path: "data/video/dummy_2.mp4"
 audio_clips:
     audio_0: "data/audio/500ms.mp3"
    #  audio_1: "data/audio/eng.wav"
 
  

